version: '3.4'

networks:
  server:

services:
  gabos_recruitment.blazor.server:
    image: ${DOCKER_REGISTRY-}gabosrecruitmentblazorserver
    build:
      context: .
      dockerfile: Gabos_Recruitment.Blazor.Server/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production 
    ports:
      - "5100:80"
    networks:
      - server
    depends_on:
      - mssqlserver


  mssqlserver:
    image: "microsoft/mssql-server-linux:2017-latest"
    container_name: mssqlserver
    ports:
      - "1410:1433" 
    networks:
      - server
    environment:
      - SA_PASSWORD=P@ssword
      - ACCEPT_EULA="Y"