version: '3.4'

networks:
  server:

services:
  gabos_recruitment.blazor.server:
    image: gabosrecruitmentblazorserver
    build:
      context: .
      dockerfile: Gabos_Recruitment.Blazor.Server/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production 
    ports:
      - "5100:80"
      - "5100:443"
    networks:
      - server
    depends_on:
      - mssqlserver


  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: mssqlserver
    ports:
      - "1433:1433" 
    networks:
      - server
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y